In [18]:
import warnings
warnings.filterwarnings('ignore')

In [19]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [20]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [21]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [22]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df = pd.get_dummies(df, columns=['home_ownership', 'verification_status', 'issue_d', 'pymnt_plan', 'initial_list_status', 
                                'next_pymnt_d', 'hardship_flag', 'application_type', 'debt_settlement_flag'])

df.head()

,loan_amnt,int_rate,installment,annual_inc,loan_status,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,hardship_flag_N,application_type_Individual,application_type_Joint App,debt_settlement_flag_N
0,10500.0,0.1719,375.35,66000.0,low_risk,27.24,0.0,0.0,8.0,0.0,...,1,1,0,1,0,1,1,1,0,1
1,25000.0,0.2000,929.09,105000.0,low_risk,20.23,0.0,0.0,17.0,1.0,...,1,1,0,1,0,1,1,1,0,1
2,20000.0,0.2000,529.88,56000.0,low_risk,24.26,0.0,0.0,8.0,0.0,...,1,1,0,1,0,1,1,1,0,1
3,10000.0,0.1640,353.55,92000.0,low_risk,31.44,0.0,1.0,10.0,1.0,...,1,1,0,1,0,1,1,1,0,1
4,22000.0,0.1474,520.39,52000.0,low_risk,18.76,0.0,1.0,14.0,0.0,...,1,1,0,1,0,1,1,1,0,1

# Split the Data into Training and Testing

In [23]:
# Create our features
X = df.drop(columns="loan_status")


# Create our target
y = df["loan_status"]

In [24]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,hardship_flag_N,application_type_Individual,application_type_Joint App,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.000000,68817.000000,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,1.0,0.860340,0.139660,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.0,0.346637,0.346637,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.0,1.000000,0.000000,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.0,1.000000,0.000000,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.0,1.000000,0.000000,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.0

In [25]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(51612, 95)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [44]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
clf = BalancedRandomForestClassifier(random_state=1).fit(X_train, y_train)
clf

BalancedRandomForestClassifier(random_state=1)

In [54]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = clf.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.7849269371623336

In [55]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[   59,    28],
       [ 1854, 15264]])

In [56]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.03      0.68      0.89      0.06      0.78      0.59        87
   low_risk       1.00      0.89      0.68      0.94      0.78      0.62     17118

avg / total       0.99      0.89      0.68      0.94      0.78      0.62     17205

In [90]:
# List the features sorted in descending order by feature importance

#sorted(zip(X.columns, clf.feature_importances_), reverse=True)
features = sorted(zip(clf.feature_importances_, X.columns), reverse=True)
for x in features:
    print (f'{x[1]}: ({x[0]})')

total_rec_prncp: (0.07758829148648667)
total_pymnt_inv: (0.058059406106283615)
total_pymnt: (0.05655856469441885)
last_pymnt_amnt: (0.05593686931051366)
total_rec_int: (0.05207556667233329)
int_rate: (0.02540598872335574)
dti: (0.018187265457160297)
out_prncp_inv: (0.01818483483486809)
installment: (0.017996605745046638)
issue_d_Jan-2019: (0.01793025665739655)
annual_inc: (0.01763197078297329)
mths_since_recent_inq: (0.017606702412191953)
revol_bal: (0.016809279327149027)
mo_sin_old_rev_tl_op: (0.016409967658404363)
max_bal_bc: (0.01622497104344834)
bc_util: (0.016112024100079923)
tot_hi_cred_lim: (0.015234553860536158)
total_rev_hi_lim: (0.014764175649881828)
bc_open_to_buy: (0.014093666069633068)
avg_cur_bal: (0.014091987429623759)
il_util: (0.014081762378987728)
mo_sin_old_il_acct: (0.013977048931123216)
mths_since_recent_bc: (0.013618662034266338)
tot_cur_bal: (0.013236505437613899)
total_il_high_credit_limit: (0.012993059280368228)
total_bc_limit: (0.01296645384923321)
loan_amnt: (0.012716177501652852)
out_prncp: (0.012685331783360674)
issue_d_Mar-2019: (0.012541454389375479)
total_bal_il: (0.012200213316294894)
mths_since_rcnt_il: (0.011883073210867377)
inq_last_12m: (0.011821714904733856)
total_bal_ex_mort: (0.011594726134057248)
all_util: (0.011532189107126363)
mo_sin_rcnt_rev_tl_op: (0.010767778435851581)
num_rev_accts: (0.010562503292810409)
num_actv_bc_tl: (0.010459340649495354)
num_op_rev_tl: (0.010350594779803973)
total_acc: (0.010104929671589017)
pct_tl_nvr_dlq: (0.010014807513705789)
open_acc: (0.009949358887762844)
num_rev_tl_bal_gt_0: (0.00978666896731181)
mo_sin_rcnt_tl: (0.009539249082813207)
total_cu_tl: (0.009416875801304217)
num_bc_tl: (0.009242008684734198)
num_il_tl: (0.009234811618968141)
num_actv_rev_tl: (0.008506986349301889)
percent_bc_gt_75: (0.007962962029562592)
acc_open_past_24mths: (0.007228153895015082)
num_bc_sats: (0.007202057651284042)
num_tl_op_past_12m: (0.007188330384026258)
open_act_il: (0.006808096428751937)
num_sats: (0.006794782141413663)
mort_acc: (0.006646823772308071)
open_rv_24m: (0.006398445220998747)
inq_fi: (0.00592181852669234)
open_il_24m: (0.005886686387116563)
inq_last_6mths: (0.005289574592910697)
open_il_12m: (0.005275166171340047)
open_rv_12m: (0.00456052396015176)
total_rec_late_fee: (0.00448227260370713)
open_acc_6m: (0.004408234756842004)
next_pymnt_d_Apr-2019: (0.004198854982433015)
issue_d_Feb-2019: (0.00393563453660668)
next_pymnt_d_May-2019: (0.0035023842102752294)
num_accts_ever_120_pd: (0.0034728742046689727)
tot_coll_amt: (0.0034422096560251174)
delinq_2yrs: (0.003189582938643175)
verification_status_Verified: (0.0031492771068162484)
home_ownership_OWN: (0.0027187113615176977)
home_ownership_RENT: (0.002519594651915735)
pub_rec: (0.002090576477924016)
application_type_Individual: (0.001955508695848118)
pub_rec_bankruptcies: (0.0018845576573990172)
verification_status_Not Verified: (0.0018844043420898778)
application_type_Joint App: (0.001461022022057769)
initial_list_status_f: (0.0013295756789926164)
home_ownership_MORTGAGE: (0.0013073524016203792)
num_tl_90g_dpd_24m: (0.0009855764048507833)
verification_status_Source Verified: (0.0009235226315099771)
initial_list_status_w: (0.0007986744672337676)
home_ownership_ANY: (0.00027200409287359305)
collections_12_mths_ex_med: (0.0001185133774607459)
chargeoff_within_12_mths: (0.00011842556281771968)
tax_liens: (0.0)
recoveries: (0.0)
pymnt_plan_n: (0.0)
policy_code: (0.0)
num_tl_30dpd: (0.0)
num_tl_120dpd_2m: (0.0)
hardship_flag_N: (0.0)
delinq_amnt: (0.0)
debt_settlement_flag_N: (0.0)
collection_recovery_fee: (0.0)
acc_now_delinq: (0.0)

### Easy Ensemble AdaBoost Classifier

In [93]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier
eec = EasyEnsembleClassifier(n_estimators=100, random_state=1).fit(X_train, y_train)
eec

EasyEnsembleClassifier(n_estimators=100, random_state=1)

In [94]:
# Calculated the balanced accuracy score
y_pred = eec.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.9258947024910258

In [ ]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

In [95]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.08      0.91      0.94      0.14      0.93      0.85        87
   low_risk       1.00      0.94      0.91      0.97      0.93      0.86     17118

avg / total       0.99      0.94      0.91      0.97      0.93      0.86     17205